services:
  # Backend Service
  - type: web
    name: dubmyyt-backend
    env: python
    buildCommand: |
      cd backend &&
      pip install --upgrade pip &&
      pip install -r requirements.txt
    startCommand: cd backend && python server.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.4
      - key: GROQ_API_KEY
        sync: false
      - key: GOOGLE_APPLICATION_CREDENTIALS_JSON
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: FLASK_ENV
        value: production
      - key: ENVIRONMENT
        value: production
    healthCheckPath: /health
    plan: free
