services:
  # Backend Service
  - type: web
    name: dubmyyt-backend
    env: python
    buildCommand: ./build_backend.sh
    startCommand: ./start_backend.sh
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.4
      - key: GROQ_API_KEY
        sync: false
      - key: GOOGLE_APPLICATION_CREDENTIALS_JSON
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: FLASK_ENV
        value: production
    healthCheckPath: /health
    plan: free

  # Frontend Service
  - type: static
    name: dubmyyt-frontend
    buildCommand: |
      cd frontend &&
      npm ci &&
      npm run build
    staticPublishPath: ./frontend/build
    envVars:
      - key: NODE_VERSION
        value: 18.17.0
      - key: REACT_APP_SUPABASE_URL
        sync: false
      - key: REACT_APP_SUPABASE_ANON_KEY
        sync: false
      - key: REACT_APP_API_BASE_URL
        value: https://dubmyyt-backend-ftv2.onrender.com
      - key: GENERATE_SOURCEMAP
        value: false
      - key: CI
        value: false
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    plan: free
