services:
  # Backend Service
  - type: web
    name: dubmyyt-backend
    env: python
    buildCommand: ./build_backend.sh
    startCommand: ./start_backend.sh
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.4
      - key: GROQ_API_KEY
        sync: false
      - key: GOOGLE_APPLICATION_CREDENTIALS_JSON
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: FLASK_ENV
        value: production
    healthCheckPath: /health
    plan: free
